spring:
  application:
    name: omg-back

  datasource:
    url: ${DB_URL_LOCAL}
    username: ${DB_USERNAME_LOCAL}
    password: ${DB_PASSWORD_LOCAL}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging.level:
  org.hibernate.SQL: debug